<?php

use Illuminate\Database\Seeder;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('list_menus')->delete();

        $data = [
                  ['id'=>'1','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Vanilla Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>'Y','created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'2','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Banana Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'3','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Oreo Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'4','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Strawberry Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'5','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Chocolate Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'6','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Blueberry Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'7','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Raspberry Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'8','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Coffee Milkshake','harga'=>'25000','keterangan'=>'Miilkshake Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'9','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Plain Lassy','harga'=>'19000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'10','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Strawberry Lassy','harga'=>'24000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'11','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Banana Lassy','harga'=>'24000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'12','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Pineapple Lassy','harga'=>'24000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'13','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Manggo Lassy','harga'=>'24000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'14','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Blueberry Lassy','harga'=>'24000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'15','id_kategori'=>'2','id_satuan'=>'1','nama_menu'=>'Raspberry Lassy','harga'=>'24000','keterangan'=>'Lassy Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'16','id_kategori'=>'3','id_satuan'=>'1','nama_menu'=>'Strawberry Smoothie','harga'=>'25000','keterangan'=>'Smoothie Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'17','id_kategori'=>'3','id_satuan'=>'1','nama_menu'=>'Banana Smoothie','harga'=>'25000','keterangan'=>'Smoothie Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'18','id_kategori'=>'3','id_satuan'=>'1','nama_menu'=>'Manggo Smoothie','harga'=>'25000','keterangan'=>'Smoothie Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'19','id_kategori'=>'3','id_satuan'=>'1','nama_menu'=>'Blueberry Smoothie','harga'=>'25000','keterangan'=>'Smoothie Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'20','id_kategori'=>'3','id_satuan'=>'1','nama_menu'=>'Raspberry Smoothie','harga'=>'25000','keterangan'=>'Smoothie Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'21','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Mango  Frullato','harga'=>'23000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'22','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Limentina','harga'=>'23000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'23','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Pome Menta','harga'=>'23000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'24','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Litchi Al Arancia','harga'=>'23000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'25','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Litchi Limonela','harga'=>'23000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'26','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Limontazera','harga'=>'23000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'27','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Giastro','harga'=>'25000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'28','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Mirtillo Menta','harga'=>'25000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'29','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Bananaberry','harga'=>'25000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'30','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Berrymia','harga'=>'25000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'31','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Avocado Nero','harga'=>'25000','keterangan'=>'Special Drink Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'32','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Papaya','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'33','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Melon','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'34','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Pineapple','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'35','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Tomato','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'36','id_kategori'=>'5','id_satuan'=>'4','nama_menu'=>'Orange','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'37','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Lime','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'38','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Banana','harga'=>'17000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'39','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Manggo','harga'=>'21000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'40','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Strawberry','harga'=>'21000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'41','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Watermelon','harga'=>'21000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'42','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Blueberry','harga'=>'23000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'43','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Avocado','harga'=>'23000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'44','id_kategori'=>'5','id_satuan'=>'1','nama_menu'=>'Raspberry','harga'=>'23000','keterangan'=>'Fresh Juice Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'45','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Pane Aglio','harga'=>'15000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'46','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Bruschetta','harga'=>'18000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'47','id_kategori'=>'6','id_satuan'=>'3','nama_menu'=>'Bruschetta al Forno','harga'=>'22000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'48','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Crostini','harga'=>'22000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'49','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Oven Baked Potato','harga'=>'22000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'50','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Panzerotti al Spinaci','harga'=>'24000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'51','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Panzerotti al Pollo','harga'=>'24000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'52','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Pipite di Pollo','harga'=>'28000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'53','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Mozzarelle Fritte','harga'=>'31000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'54','id_kategori'=>'6','id_satuan'=>'4','nama_menu'=>'Piatto Soffritto','harga'=>'35000','keterangan'=>'Antipasti Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'55','id_kategori'=>'7','id_satuan'=>'3','nama_menu'=>'Minestrone','harga'=>'27000','keterangan'=>'Zupe Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'56','id_kategori'=>'7','id_satuan'=>'3','nama_menu'=>'Funghi','harga'=>'27000','keterangan'=>'Zupe Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'57','id_kategori'=>'7','id_satuan'=>'3','nama_menu'=>'Pomodori e Basilico','harga'=>'27000','keterangan'=>'Zupe Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'58','id_kategori'=>'7','id_satuan'=>'3','nama_menu'=>'Del Mare','harga'=>'30000','keterangan'=>'Zupe Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'59','id_kategori'=>'7','id_satuan'=>'3','nama_menu'=>'Bocconcini','harga'=>'30000','keterangan'=>'Zupe Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'60','id_kategori'=>'8','id_satuan'=>'4','nama_menu'=>'Insalata Caesaro','harga'=>'36000','keterangan'=>'Insalata','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'61','id_kategori'=>'8','id_satuan'=>'4','nama_menu'=>'Insalata Primavera','harga'=>'36000','keterangan'=>'Insalata','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'62','id_kategori'=>'8','id_satuan'=>'4','nama_menu'=>'Insalata la Marche','harga'=>'36000','keterangan'=>'Insalata','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'63','id_kategori'=>'8','id_satuan'=>'4','nama_menu'=>'Insalata di Tonno','harga'=>'36000','keterangan'=>'Insalata','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'64','id_kategori'=>'8','id_satuan'=>'4','nama_menu'=>'Insalata Mediterranea','harga'=>'36000','keterangan'=>'Insalata','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'65','id_kategori'=>'9','id_satuan'=>'4','nama_menu'=>'Panino di Verdure','harga'=>'38000','keterangan'=>'Panini Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'66','id_kategori'=>'9','id_satuan'=>'4','nama_menu'=>'Panino di Carne','harga'=>'38000','keterangan'=>'Panini Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'67','id_kategori'=>'9','id_satuan'=>'4','nama_menu'=>'Panino al Tonno e Uovo','harga'=>'38000','keterangan'=>'Panini Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'68','id_kategori'=>'9','id_satuan'=>'4','nama_menu'=>'Panino al Pollo e Pesto','harga'=>'38000','keterangan'=>'Panini Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'69','id_kategori'=>'9','id_satuan'=>'4','nama_menu'=>'Panino Calabrese','harga'=>'38000','keterangan'=>'Panini Menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'70','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Spaghetti Aglio e Qlio','harga'=>'32000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'71','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Spaghetti alla Crudaida','harga'=>'32000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'72','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Fettucine al Pesto','harga'=>'35000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'73','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Fettucine Funghi','harga'=>'35000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'74','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Fettucine Alfredo','harga'=>'35000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'75','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Fettucine Carbonara','harga'=>'35000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'76','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Penne al Arrabiata','harga'=>'35000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'77','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Spaghetti Bolognese','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'78','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Spaghetti al Tonno Piccante','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'79','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Penne con Pollo e Patate','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'80','id_kategori'=>'10','id_satuan'=>'3','nama_menu'=>'Spaghetti Marinara','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'81','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Penne al Pollo Picante','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'82','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Ndundari al Ricotta','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'83','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Lasagna Classica','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'84','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Ravioli Nanazzita','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'85','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Cannelonni ai Spinci','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'86','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Cannelonni al Tonno','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'87','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Penne Salmone','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'88','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Tortellini con Salsa di Noci','harga'=>'39000','keterangan'=>'Primi Piati menu','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'89','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Body Purification','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'90','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Power Detox','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'91','id_kategori'=>'1','id_satuan'=>'1','nama_menu'=>'Stunning Skin','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'92','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Healthy Booster','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'93','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Cool Refreshing','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'94','id_kategori'=>'4','id_satuan'=>'1','nama_menu'=>'Whole Coconut','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'95','id_kategori'=>'10','id_satuan'=>'4','nama_menu'=>'Penne Salomone','harga'=>'39000','keterangan'=>'','id_size'=>NULL,'trash'=>'Y','created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'96','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Petto di Pollo','harga'=>'56000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'97','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Pollo ala Nanamia','harga'=>'63000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'98','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Polpettoni','harga'=>'63000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'99','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Involtini di Manzo','harga'=>'69000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'100','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Brasato','harga'=>'69000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'101','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Farsumagru','harga'=>'69000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'102','id_kategori'=>'11','id_satuan'=>'4','nama_menu'=>'Calamaro Ripiena','harga'=>'75000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'103','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Margherita R','harga'=>'41000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'104','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Margherita L','harga'=>'51000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'105','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Mariazzita R','harga'=>'49000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'106','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Mariazzita L','harga'=>'59000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'107','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Toscana R','harga'=>'49000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'108','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Toscana L','harga'=>'59000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'109','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Hawaii R','harga'=>'49000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'110','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Hawaii L','harga'=>'59000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'111','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Giovanni R','harga'=>'49000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'112','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Giovanni L','harga'=>'59000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'113','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Nanamia Speciale R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'114','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Nanamia Speciale L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'115','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Al Tonno R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'116','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Al Tonno L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'117','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Spinaci R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'118','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Spinaci L','harga'=>'55000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'119','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Vegetariana R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'120','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Vegetariana L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'121','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Paesana R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'122','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Paesana L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'123','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pollo Funghi R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'124','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pollo Funghi L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'125','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Mediterranea R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'126','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Mediterranea L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'127','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Rustica R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'128','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Rustica L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'129','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Napoli R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'130','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Napoli L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'131','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Capriciosa R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'132','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Capriciosa L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'133','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Peperoni R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'134','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Peperoni L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'135','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Molta Gusta R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'136','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Molta Gusta L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'137','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Casa Linga R','harga'=>'55000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'138','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Casa Linga L','harga'=>'65000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'139','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Terra Nostra R','harga'=>'60000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'140','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Terra Nostra L','harga'=>'70000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'141','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Carne R','harga'=>'60000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'142','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Carne L','harga'=>'70000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'143','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Pizza Diavola R','harga'=>'60000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'144','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Pizza Diavola L','harga'=>'70000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'145','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Quattro Stagioni R','harga'=>'60000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'146','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Quattro Stagioni L','harga'=>'70000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'147','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Quattro Formaggi R','harga'=>'60000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'148','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Quattro Formaggi L','harga'=>'70000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'149','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Calzone Vegetariana','harga'=>'59000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'150','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Fruitti di Mare R','harga'=>'60000','keterangan'=>'','id_size'=>'2','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'151','id_kategori'=>'24','id_satuan'=>'6','nama_menu'=>'Fruitti di Mare L','harga'=>'70000','keterangan'=>'','id_size'=>'3','trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'152','id_kategori'=>'24','id_satuan'=>'5','nama_menu'=>'Calzone al Forno','harga'=>'65000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'153','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Espresso','harga'=>'16000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'154','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Double Espresso','harga'=>'25000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'155','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Espresso Macchiato','harga'=>'19000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'156','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Americano','harga'=>'19000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'157','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Americano','harga'=>'19000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'158','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Cappucino','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'159','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Cappucino','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'160','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Latte Machiato','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'161','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Caffe Latte','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'162','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Coffe Latte','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'163','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Vanilla Latte','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'164','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Vanilla Latte','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'165','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Jam Hazelnut','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'166','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Jam Hazelnut','harga'=>'22000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'167','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Mochacino','harga'=>'24000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'168','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Mochacino','harga'=>'24000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'169','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Hot Chocolate','harga'=>'24000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'170','id_kategori'=>'13','id_satuan'=>'1','nama_menu'=>'Ice Chocolate','harga'=>'24000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'171','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Mineral Water','harga'=>'8000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'172','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Coca Cola','harga'=>'10000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'173','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Soda Water','harga'=>'10000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'174','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Sprite','harga'=>'10000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'175','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Hot Tea','harga'=>'10000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'176','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Ice Tea','harga'=>'10000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'177','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Hot Lemon Tea','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'178','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Ice Lemon Tea','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'179','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Hot Orange','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'180','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Ice Orange','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'181','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Ice Lime','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'182','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Hot Lime','harga'=>'14000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'183','id_kategori'=>'25','id_satuan'=>'2','nama_menu'=>'Coca Cola Zero','harga'=>'18000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'184','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Cola Float','harga'=>'18000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'185','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Lime Squash','harga'=>'18000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'186','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Orange Squash','harga'=>'18000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'187','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Infuso Miele','harga'=>'18000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'188','id_kategori'=>'25','id_satuan'=>'1','nama_menu'=>'Spezi','harga'=>'18000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'189','id_kategori'=>'26','id_satuan'=>'1','nama_menu'=>'Gelato Cioccolato','harga'=>'17000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'190','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Panna Cotta','harga'=>'27000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'191','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Dolce Vita','harga'=>'27000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'192','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Creme di Cioccolato','harga'=>'27000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'193','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Creme Brulee','harga'=>'27000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'194','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Tiramisu Italiano','harga'=>'29000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'195','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Torta di Mirtilli','harga'=>'29000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'196','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Torta Mia','harga'=>'29000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')],
                  ['id'=>'197','id_kategori'=>'26','id_satuan'=>'8','nama_menu'=>'Strudel di Mele','harga'=>'29000','keterangan'=>'','id_size'=>NULL,'trash'=>NULL,'created_at'=>date('Y-1-1 H:i:s')]

            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
            // ['id'=>1,'id_kategori'=>'xxx','id_satuan'=>'Satuan','nama_menu'=>'Menu','harga'=>'Harga','keterangan'=>'Keter','id_size'=>'Size','created_at'=>date('Y-m-d H:i:s')],
        ];

        \DB::table('list_menus')->insert($data);
    }
}
